import type { GameConfig, Item, Location } from './types';
export const ITEMS: Item[] = [
  {
    id: 'food',
    name: 'Harvest bowl',
    category: 'Food',
    rarity: 'Common',
    price: 25,
    description: 'A wholesome meal. Restores 30 fullness.',
    icon: '🍲',
  },
  {
    id: 'exp_bottle',
    name: 'Stardust elixir',
    category: 'EXP items',
    rarity: 'Rare',
    price: 100,
    description: '+620 EXP. A little bottled possibility.',
    icon: '🧪',
  },
  {
    id: 'level_bottle',
    name: 'Growth nectar',
    category: 'Level items',
    rarity: 'Epic',
    price: 600,
    description: 'Advance exactly 1.2 levels of progress.',
    icon: '⚗️',
  },
  {
    id: 'potion',
    name: 'Wildflower tonic',
    category: 'Battle items',
    rarity: 'Common',
    price: 60,
    description: 'Restore 40 HP during battle.',
    icon: '💚',
  },
  {
    id: 'brush',
    name: 'Cloud-soft brush',
    category: 'Care',
    rarity: 'Common',
    price: 40,
    description: 'Restore 40 cleanliness.',
    icon: '🪮',
  },
  {
    id: 'toy',
    name: 'Moon yarn',
    category: 'Care',
    rarity: 'Rare',
    price: 80,
    description: 'Restore 25 happiness and 3 bond.',
    icon: '🧶',
  },
  {
    id: 'ribbon',
    name: 'Meadow ribbon',
    category: 'Cosmetics',
    rarity: 'Common',
    price: 200,
    description: 'A keepsake in soft meadow green.',
    icon: '🎀',
  },
  {
    id: 'moon_collar',
    name: 'Moonstone collar',
    category: 'Cosmetics',
    rarity: 'Rare',
    price: 700,
    description: 'A tiny moon that follows you home.',
    icon: '🌙',
  },
  {
    id: 'star_crown',
    name: 'Starlight crown',
    category: 'Cosmetics',
    rarity: 'Epic',
    price: 1800,
    description: 'For a very good little adventurer.',
    icon: '👑',
  },
  {
    id: 'aurora',
    name: 'Aurora aura',
    category: 'Cosmetics',
    rarity: 'Legendary',
    price: 4500,
    description: 'Dancing ribbons of northern light.',
    icon: '🌌',
  },
  {
    id: 'moon_fox',
    name: 'Celestial familiar',
    category: 'Cosmetics',
    rarity: 'Mythic',
    price: 0,
    description: 'The featured dream of the Moonwell banner.',
    icon: '🦊',
  },
  {
    id: 'ticket',
    name: 'Wish ticket',
    category: 'Gacha items',
    rarity: 'Rare',
    price: 0,
    description: 'Earned through play. One wish at the Moonwell.',
    icon: '🎟️',
  },
  {
    id: 'fusion_token',
    name: 'Fusion prism',
    category: 'Fusion items',
    rarity: 'Epic',
    price: 1000,
    description: 'Open one new fusion session at level 10.',
    icon: '💎',
  },
  {
    id: 'event_leaf',
    name: 'Moonlit garland',
    category: 'Event items',
    rarity: 'Epic',
    price: 0,
    description: 'A keepsake from the Harvest Moon festival.',
    icon: '🍃',
  },
];
export const LOCATIONS: Location[] = [
  [
    1,
    'Whispering Meadow',
    1,
    'Thorn Boar',
    'The grasses remember every pawprint.',
    '#95c3a0',
    47,
    42,
  ],
  [
    2,
    'Moonlit Woods',
    10,
    'Shadow Cat',
    'Follow the lanterns between the dreaming trees.',
    '#91bfc1',
    34,
    33,
  ],
  [
    3,
    'Crystal Coast',
    20,
    'Rogue Fox',
    'Tide pools hold fragments of fallen stars.',
    '#68cbd9',
    39,
    60,
  ],
  [
    4,
    'Ember Canyon',
    30,
    'Stone Bear',
    'Warm winds carry the song of ancient embers.',
    '#dfab77',
    64,
    47,
  ],
  [
    5,
    'Skygarden Peaks',
    40,
    'Storm Griffin',
    'Gardens bloom where the clouds meet the sky.',
    '#e4d8a1',
    85,
    24,
  ],
  [
    6,
    'Neon Rainforest',
    50,
    'Corrupted Wolf',
    'Bioluminescent leaves light a hidden path.',
    '#67d0b5',
    12,
    46,
  ],
  [
    7,
    'Frostfang Valley',
    60,
    'Ice Tiger',
    'Listen for the quiet heartbeat beneath the snow.',
    '#b5d6e8',
    49,
    18,
  ],
  [
    8,
    'Celestial Ruins',
    70,
    'Void Serpent',
    'Old constellations wait to be remembered.',
    '#c2b0ed',
    61,
    25,
  ],
  [
    9,
    'Eclipse Sanctuary',
    80,
    'Eclipse Lynx',
    'A brave heart can find light in the longest shadow.',
    '#cfa0ba',
    15,
    17,
  ],
  [
    10,
    'Astral Wilds',
    90,
    'Corrupted Chimera',
    'Beyond the last star, your story is still unfolding.',
    '#b6a3f5',
    84,
    78,
  ],
].map(([id, name, level, enemy, lore, color, x, y]) => ({
  id,
  name,
  level,
  enemy,
  lore,
  color,
  x,
  y,
})) as Location[];
export const DEFAULT_CONFIG: GameConfig = {
  name: 'FurEver',
  maintenance: false,
  prices: Object.fromEntries(
    ITEMS.filter((i) => i.price > 0).map((i) => [i.id, i.price]),
  ),
  expBottle: 620,
  dailyCoins: 200,
  dailyXp: 300,
  groomCoins: 100,
  playCoins: 150,
  minigameLimit: 5,
  moraRate: 10,
  gachaWeights: [45, 30, 15, 8, 2],
  pity: { epic: 10, legendary: 50, mythic: 100 },
  event: {
    id: 'harvest-moon-2026',
    name: 'Harvest Moon',
    lore: 'Gather moon petals beneath the silver trees. The Moon Fox has a gift for companions who explore together.',
    starts: '2026-09-01T00:00:00Z',
    ends: '2026-10-01T00:00:00Z',
    featured: 'Moon Fox',
  },
  packages: [
    {
      id: 'starter',
      name: 'Starter Pouch',
      coins: 500,
      amount: 299,
      currency: 'usd',
      enabled: false,
    },
    {
      id: 'small',
      name: 'Small Chest',
      coins: 1100,
      amount: 599,
      currency: 'usd',
      enabled: false,
    },
    {
      id: 'explorer',
      name: 'Explorer Chest',
      coins: 3000,
      amount: 1499,
      currency: 'usd',
      enabled: false,
    },
    {
      id: 'royal',
      name: 'Royal Chest',
      coins: 7000,
      amount: 2999,
      currency: 'usd',
      enabled: false,
    },
    {
      id: 'mythic',
      name: 'Mythic Vault',
      coins: 15000,
      amount: 5999,
      currency: 'usd',
      enabled: false,
    },
  ],
};
export const DAILY_TASKS = [
  ['feed', 'Serve a harvest bowl'],
  ['groom', 'Groom your companion'],
  ['minigame', 'Finish a minigame'],
  ['battle', 'Win a battle'],
  ['explore', 'Finish an expedition'],
  ['exp', 'Use an EXP bottle'],
  ['bond', 'Spend a moment together'],
];
export const ACHIEVEMENTS = [
  ['first_steps', 'First Steps'],
  ['first_battle', 'First Battle'],
  ['perfect_groom', 'Perfect Groom'],
  ['best_friend', 'Best Friend'],
  ['treasure_hunter', 'Treasure Hunter'],
  ['level_10', 'A New Horizon'],
  ['level_25', 'Growing Together'],
  ['level_50', 'Halfway to the Stars'],
  ['level_75', 'A Legendary Bond'],
  ['level_100', 'FurEver Friends'],
  ['lucky_pull', 'Written in the Stars'],
  ['legendary_collector', 'Legendary Collector'],
  ['fusion_pioneer', 'Fusion Pioneer'],
];
